In [1]:
import numpy as np

In [2]:
W = np.array([[1, 2, 3, 4],
             [0,0,1,0],
             [1,1,1,1],
             [0,0,0,0],
             [9,0,9,0]])

x = np.array([[1,1,1,1]])
W.shape

(5, 4)

In [3]:
np.dot(W,x.transpose())


array([[10],
       [ 1],
       [ 4],
       [ 0],
       [18]])

In [4]:
# y = f(Wx +b)
# dJ/dy -> m x 1 vector
# dJ/dW -> dJ/dy * dy/dW

dJ = np.array([[1,0,2,0,1]])

#np.outer(dJ, x).shape
np.outer(x, dJ).shape


(4, 5)

In [5]:
num_hidden_units = 10
num_ftrs = 400

np.zeros((num_hidden_units, num_ftrs))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
init_values = {
    "W1": np.zeros((num_hidden_units, num_ftrs)),
    "b1": np.zeros(num_hidden_units),
    "W2": np.zeros((1, num_hidden_units)),
    "b2": np.array(0.0)
}

In [7]:
init_values

{'W1': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'b1': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'W2': array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 'b2': array(0.)}

In [18]:
num_instances = 100
np.random.permutation(num_instances)

array([ 3, 44, 63, 33, 28,  9, 80, 60, 10, 82, 71, 17, 51, 18, 19,  0, 91,
       32, 89, 14, 20, 81, 21,  4, 58, 39, 64, 74, 99, 97, 77, 65, 75, 96,
       26,  5, 35, 13, 83, 54, 37, 94, 90, 66, 29, 50,  8, 76, 53, 45,  6,
       41, 52, 11,  7, 25, 68, 70, 48, 62, 86, 36, 12, 93, 85, 40, 95, 61,
       34, 92, 55, 67, 46, 98, 31, 49, 84, 27, 38, 30, 87, 23,  2,  1, 57,
       43, 72, 24, 73, 78, 42, 59, 56, 47, 22, 15, 79, 16, 69, 88])

In [21]:
x = np.array([1,1,1,1])
y = np.array([0,1,0,1])

In [23]:
np.dot(x,y)

AttributeError: 'numpy.ndarray' object has no attribute 'tranpose'

In [26]:
x = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0,])

In [27]:
np.tanh(x)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])